# Generated by Django 3.1.7 on 2021-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaafilm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
