# Generated by Django 3.1.7 on 2021-04-26 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recaafilm', '0002_auto_20210426_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Watcher',
        ),
    ]
